### PR TITLE
Universal ERC-20 Wrapper

### PR DESCRIPTION
**Pull request by RogerPodacter**

### CODE REVIEW

**Comment by RogerPodacter** [comment]
The idea is to pair it with a smart contract like this:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

import "solady/src/tokens/ERC20.sol";
import "solady/src/utils/ECDSA.sol";
import "solady/src/utils/EIP712.sol";
import "solady/src/utils/LibString.sol";
import "solady/src/utils/SafeTransferLib.sol";
import "solady/src/utils/ERC1967Factory.sol";
import "solady/src/utils/ERC1967FactoryConstants.sol";

contract FacetERC20Bridge is EIP712 {
    using SafeTransferLib for address;
    using LibString for *;
    using ECDSA for bytes32;

    event ethscriptions_protocol_CreateEthscription(
        address indexed initialOwner,
        string contentURI
    );

    struct WithdrawRequest {
        address recipient;
        uint256 amount;
        address tokenSmartContract;
        bytes32 withdrawalId;
        bytes32 blockHash;
        uint256 blockNumber;
        bytes signature;
    }
    
    struct BridgeStorage {
        mapping(bytes32 => bool) processedWithdraws;
        bool depositEnabled;
        bool withdrawEnabled;
        address adminAddress;
        address signerAddress;
        address dumbContractAddress;
        uint256 cancelBlockNumber;
        uint256 withdrawDelay;
    }
    
    function s() internal pure returns (BridgeStorage storage cs) {
        bytes32 position = keccak256("BridgeStorage.contract.storage.v1");
        assembly {
           cs.slot := position
        }
    }
    
    modifier onlyAdmin() {
        require(msg.sender == adminOfProxy(), "Not admin");
        _;
    }
    
    function initialize(
        address adminAddress
    ) external {
        require(msg.sender == ERC1967FactoryConstants.ADDRESS, "Not factory");
        require(s().adminAddress == address(0), "Already initialized");
        require(adminAddress != address(0), "No zero address");

        s().adminAddress = adminAddress;
    }
    
    function adminOfProxy() public view returns (address) {
        return ERC1967Factory(ERC1967FactoryConstants.ADDRESS).adminOf(address(this));
    }
    
    function deposit(
        address tokenSmartContract,
        uint256 amount,
        address recipient
    ) external {
        require(amount > 0, "Invalid amount");
        require(s().depositEnabled, "Deposit disabled");

        tokenSmartContract.safeTransferFrom(msg.sender, address(this), amount);
        
        ERC20 token = ERC20(tokenSmartContract);
        
        uint8 decimals = token.decimals();
        string memory symbol = token.symbol();
        string memory name = token.name();
        
        require(decimals <= 18, "Invalid decimals");
        require(bytes(symbol).length <= 25, "Invalid symbol");
        require(bytes(name).length <= 25, "Invalid name");

        bytes memory out = abi.encodePacked(
            'data:application/vnd.facet.tx+json;rule=esip6,{"op":"call","data":{"to":"',
            s().dumbContractAddress.toHexString(),
            '","function":"bridgeIn","args":{"to":"',
            recipient.toHexString(),
            '","amount":"',
            amount.toString(),
            '","decimals":',
            uint256(decimals).toString(),
            ',"symbol":"',
            symbol.escapeJSON(),
            '","name":"',
            name.escapeJSON(),
            '","tokenSmartContract":"',
            tokenSmartContract.toHexString(),
            '"}}}'
        );
        
        emit ethscriptions_protocol_CreateEthscription(0x00000000000000000000000000000000000FacE7, string(out));
    }

    function withdraw(
        WithdrawRequest calldata req
    ) external {
        require(s().withdrawEnabled, "Withdraw disabled");

        bytes32 hashedMessage = _hashTypedData(keccak256(abi.encode(
            keccak256(
                "Withdraw(address recipient,address dumbContract,uint256 amount,address tokenSmartContract"
                "bytes32 withdrawalId,bytes32 blockHash,uint256 blockNumber)"
            ),
            req.recipient,
            s().dumbContractAddress,
            req.amount,
            req.tokenSmartContract,
            req.withdrawalId,
            req.blockHash,
            req.blockNumber
        )));

        address signer = hashedMessage.recoverCalldata(req.signature);

        require(signer == s().signerAddress, "Invalid signature");
        require(!s().processedWithdraws[req.withdrawalId], "Already processed");
        require(s().cancelBlockNumber <= req.blockNumber, "Signature canceled");
        require(block.number >= req.blockNumber + s().withdrawDelay, "Withdraw delay");
        require(req.blockHash == bytes32(0) || blockhash(req.blockNumber) == req.blockHash, "Invalid block number or hash");

        s().processedWithdraws[req.withdrawalId] = true;
        
        req.tokenSmartContract.safeTransfer(req.recipient, req.amount);
        
        string memory out = string.concat(
            'data:application/vnd.facet.tx+json;rule=esip6,{"op":"call","data":{"to":"',
            s().dumbContractAddress.toHexString(),
            '","function":"markWithdrawalComplete","args":{"to":"',
            req.recipient.toHexString(),
            '","withdrawalId":"',
            uint256(req.withdrawalId).toHexString(32),
            '","tokenSmartContract":"',
            req.tokenSmartContract.toHexString(),
            '"}}}'
        );
        
        emit ethscriptions_protocol_CreateEthscription(0x00000000000000000000000000000000000FacE7, string(out));
    }
    
    function setWithdrawEnabled(bool enabled) external onlyAdmin {
        s().withdrawEnabled = enabled;
    }
    
    function setDepositEnabled(bool enabled) external onlyAdmin {
        s().depositEnabled = enabled;
    }

    function enableAllFeatures() external onlyAdmin {
        s().depositEnabled = true;
        s().withdrawEnabled = true;
    }
    
    function disableAllFeatures() external onlyAdmin {
        s().depositEnabled = false;
        s().withdrawEnabled = false;
    }
    
    function cancelSignatures() external onlyAdmin {
        s().cancelBlockNumber = block.number;
    }
    
    function setDumbContract(address dumbContract) external onlyAdmin {
        s().dumbContractAddress = dumbContract;
    }
    
    function setSigner(address signer) external onlyAdmin {
        s().signerAddress = signer;
    }
    
    function setAdmin(address admin) external onlyAdmin {
        s().adminAddress = admin;
    }
    
    function setWithdrawDelay(uint256 withdrawDelay) external onlyAdmin {
        s().withdrawDelay = withdrawDelay;
    }
    
    function getSigner() external view returns (address) {
        return s().signerAddress;
    }
    
    function getAdmin() external view returns (address) {
        return s().adminAddress;
    }
    
    function getWithdrawDelay() external view returns (uint256) {
        return s().withdrawDelay;
    }
    
    function getDumbContract() external view returns (address) {
        return s().dumbContractAddress;
    }
    
    function getCancelBlockNumber() external view returns (uint256) {
        return s().cancelBlockNumber;
    }
    
    function getDepositEnabled() external view returns (bool) {
        return s().depositEnabled;
    }
    
    function getWithdrawalEnabled() external view returns (bool) {
        return s().withdrawEnabled;
    }
    
    function processedWithdraws(bytes32 withdrawalId) external view returns (bool) {
        return s().processedWithdraws[withdrawalId];
    }

    function _domainNameAndVersion() 
        internal
        pure
        override
        returns (string memory name, string memory version)
    {
        name = "Facet ERC20 Bridge";
        version = "1";
    }
}
```

**Comment by drewroberts** [comment]
Wow.

**Comment by RogerPodacter** [comment]
Thanks, @drewroberts! BTW this is still being developed in https://github.com/0xFacet/facet-vm/pull/190. This pull got closed in the goerli => sepolia migration

**Comment by drewroberts** [comment]
Thank you. Continuing my journey down the rabbit hole there..

**Pull request closed without merging**
